version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:0zp9AZY9+uKbGfnI2wYGid7hNw7wiEVnqSvQQB8RRXo rahul.kumar@healthians.com SSH Key"
            commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
       

      
 
