      version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:0zp9AZY9+uKbGfnI2wYGid7hNw7wiEVnqSvQQB8RRXo rahul.kumar@healthians.com SSH Key"
       

      
 
