version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:0zp9AZY9+uKbGfnI2wYGid7hNw7wiEVnqSvQQB8RRXo rahul.kumar@healthians.com SSH Key"
    
        
       

      
 
